CONFIG_FCM_API_KEY_FIREBASE: AAAAIag5n60:APA91bGJqnvQ5eKg1NY1HIVs-pMcR0X0Avs8GIqWYHtRz5Tmmn8gEcEHogzvY6NuH2EPMxWlv88gV5bvbL8J03wwn5wGzbsqpmazHKwHv2nifqbKxMIfwlUXQLu0YhVPIF2tTxe0PNhB
CONFIG_FCM_API_KEY: AIzaSyAogkNwPUicGPQIqRB9uji0bsavRo8ZfmM
CONFIG_FCM_AUTH_DOMAIN: warashibe-4a5e1.firebaseapp.com
CONFIG_FCM_DB_URL: https://warashibe-4a5e1.firebaseio.com
CONFIG_FCM_PROJECT_ID: warashibe-4a5e1
CONFIG_FCM_STORAGE_BUCKET: warashibe-4a5e1.appspot.com
CONFIG_FCM_MESSAGING_SENDER_ID: 144556269485
CONFIG_FCM_APP_ID: 1:144556269485:web:b3d0912b13a5f11c0d0b24
CONFIG_FCM_MEASUREMENT_ID: G-XZFQJL6SLG

BASE_URL: http://50.19.141.107/